name: CI/CD Pipeline for Helm

on:
  workflow_run:
    workflows: ["pages-build-deployment"]  # GitHub Pages 빌드 완료 후 실행
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 소스 코드 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Helm 설치
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      # .kube 디렉토리 생성
    - name: Create .kube directory
      run: |
        mkdir -p $HOME/.kube
    # 3. Kubernetes 컨텍스트 설정 (KUBECONFIG 환경 변수 사용)
    - name: Set up KUBECONFIG
      run: |
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
      env:
        KUBECONFIG: $HOME/.kube/config

    # 4. Helm 차트 배포
    - name: Deploy Helm chart
      run: |
        helm repo add my-repo https://hae-gun.github.io/k3s-repository/
        helm repo update
        helm upgrade --install my-nginx my-repo/my-temp-chart --set image.tag=latest
