name: CI/CD Pipeline for Helm

# 파이프라인이 트리거될 조건 설정 (브랜치 push)
on:
  push:
    branches:
      - gh-pages  # main 브랜치에 푸시될 때 파이프라인 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 소스 코드 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Helm 설치
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    # 3. Kubernetes 컨텍스트 설정 (KUBECONFIG 환경 변수 사용)
    - name: Set up KUBECONFIG
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}  # Kubernetes 설정 파일을 GitHub Secrets로 관리
      run: |
        echo "$KUBECONFIG" > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig

    # 4. Helm 차트 배포
    - name: Deploy Helm chart
      run: |
        helm repo add my-repo https://hae-gun.github.io/k3s-repository/
        helm repo update
        helm upgrade --install my-nginx my-repo/my-temp-chart --set image.tag=latest
