name: CI/CD Pipeline for Helm

on:
  workflow_run:
    workflows: ["pages-build-deployment"]  # GitHub Pages 빌드 완료 후 실행
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 소스 코드 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Helm 설치
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    
